/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'deckdeckgo';
import 'deckdeckgo-charts';
import 'deckdeckgo-highlight-code';
import 'deckdeckgo-qrcode';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppLogo {}
  interface AppLogoAttributes extends StencilHTMLAttributes {}

  interface AppMenuFooter {}
  interface AppMenuFooterAttributes extends StencilHTMLAttributes {}

  interface AppNavigation {
    'logo': boolean;
    'menuToggle': boolean;
    'navigation': boolean;
  }
  interface AppNavigationAttributes extends StencilHTMLAttributes {
    'logo'?: boolean;
    'menuToggle'?: boolean;
    'navigation'?: boolean;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsChart {}
  interface AppComponentsChartAttributes extends StencilHTMLAttributes {}

  interface AppComponentsGif {}
  interface AppComponentsGifAttributes extends StencilHTMLAttributes {}

  interface AppComponentsHighlightCode {}
  interface AppComponentsHighlightCodeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsQrcode {}
  interface AppComponentsQrcodeAttributes extends StencilHTMLAttributes {}

  interface AppComponentsSocial {}
  interface AppComponentsSocialAttributes extends StencilHTMLAttributes {}

  interface AppComponentsYoutube {}
  interface AppComponentsYoutubeAttributes extends StencilHTMLAttributes {}

  interface AppDeckNavigation {}
  interface AppDeckNavigationAttributes extends StencilHTMLAttributes {}

  interface AppDeckPager {}
  interface AppDeckPagerAttributes extends StencilHTMLAttributes {}

  interface AppDeckSize {}
  interface AppDeckSizeAttributes extends StencilHTMLAttributes {}

  interface AppEditDefault {}
  interface AppEditDefaultAttributes extends StencilHTMLAttributes {}

  interface AppEditMarkdown {}
  interface AppEditMarkdownAttributes extends StencilHTMLAttributes {}

  interface AppInstallation {}
  interface AppInstallationAttributes extends StencilHTMLAttributes {}

  interface AppIntroduction {}
  interface AppIntroductionAttributes extends StencilHTMLAttributes {}

  interface AppSlideAuthor {}
  interface AppSlideAuthorAttributes extends StencilHTMLAttributes {}

  interface AppSlideChart {}
  interface AppSlideChartAttributes extends StencilHTMLAttributes {}

  interface AppSlideCode {}
  interface AppSlideCodeAttributes extends StencilHTMLAttributes {}

  interface AppSlideContent {}
  interface AppSlideContentAttributes extends StencilHTMLAttributes {}

  interface AppSlideGif {}
  interface AppSlideGifAttributes extends StencilHTMLAttributes {}

  interface AppSlideQrcode {}
  interface AppSlideQrcodeAttributes extends StencilHTMLAttributes {}

  interface AppSlideSplit {}
  interface AppSlideSplitAttributes extends StencilHTMLAttributes {}

  interface AppSlideTitle {}
  interface AppSlideTitleAttributes extends StencilHTMLAttributes {}

  interface AppSlideYoutube {}
  interface AppSlideYoutubeAttributes extends StencilHTMLAttributes {}

  interface AppSlidesBackground {}
  interface AppSlidesBackgroundAttributes extends StencilHTMLAttributes {}

  interface AppSlidesConcept {}
  interface AppSlidesConceptAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppFooter': Components.AppFooter;
    'AppLogo': Components.AppLogo;
    'AppMenuFooter': Components.AppMenuFooter;
    'AppNavigation': Components.AppNavigation;
    'AppHome': Components.AppHome;
    'AppComponentsChart': Components.AppComponentsChart;
    'AppComponentsGif': Components.AppComponentsGif;
    'AppComponentsHighlightCode': Components.AppComponentsHighlightCode;
    'AppComponentsQrcode': Components.AppComponentsQrcode;
    'AppComponentsSocial': Components.AppComponentsSocial;
    'AppComponentsYoutube': Components.AppComponentsYoutube;
    'AppDeckNavigation': Components.AppDeckNavigation;
    'AppDeckPager': Components.AppDeckPager;
    'AppDeckSize': Components.AppDeckSize;
    'AppEditDefault': Components.AppEditDefault;
    'AppEditMarkdown': Components.AppEditMarkdown;
    'AppInstallation': Components.AppInstallation;
    'AppIntroduction': Components.AppIntroduction;
    'AppSlideAuthor': Components.AppSlideAuthor;
    'AppSlideChart': Components.AppSlideChart;
    'AppSlideCode': Components.AppSlideCode;
    'AppSlideContent': Components.AppSlideContent;
    'AppSlideGif': Components.AppSlideGif;
    'AppSlideQrcode': Components.AppSlideQrcode;
    'AppSlideSplit': Components.AppSlideSplit;
    'AppSlideTitle': Components.AppSlideTitle;
    'AppSlideYoutube': Components.AppSlideYoutube;
    'AppSlidesBackground': Components.AppSlidesBackground;
    'AppSlidesConcept': Components.AppSlidesConcept;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-logo': Components.AppLogoAttributes;
    'app-menu-footer': Components.AppMenuFooterAttributes;
    'app-navigation': Components.AppNavigationAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-components-chart': Components.AppComponentsChartAttributes;
    'app-components-gif': Components.AppComponentsGifAttributes;
    'app-components-highlight-code': Components.AppComponentsHighlightCodeAttributes;
    'app-components-qrcode': Components.AppComponentsQrcodeAttributes;
    'app-components-social': Components.AppComponentsSocialAttributes;
    'app-components-youtube': Components.AppComponentsYoutubeAttributes;
    'app-deck-navigation': Components.AppDeckNavigationAttributes;
    'app-deck-pager': Components.AppDeckPagerAttributes;
    'app-deck-size': Components.AppDeckSizeAttributes;
    'app-edit-default': Components.AppEditDefaultAttributes;
    'app-edit-markdown': Components.AppEditMarkdownAttributes;
    'app-installation': Components.AppInstallationAttributes;
    'app-introduction': Components.AppIntroductionAttributes;
    'app-slide-author': Components.AppSlideAuthorAttributes;
    'app-slide-chart': Components.AppSlideChartAttributes;
    'app-slide-code': Components.AppSlideCodeAttributes;
    'app-slide-content': Components.AppSlideContentAttributes;
    'app-slide-gif': Components.AppSlideGifAttributes;
    'app-slide-qrcode': Components.AppSlideQrcodeAttributes;
    'app-slide-split': Components.AppSlideSplitAttributes;
    'app-slide-title': Components.AppSlideTitleAttributes;
    'app-slide-youtube': Components.AppSlideYoutubeAttributes;
    'app-slides-background': Components.AppSlidesBackgroundAttributes;
    'app-slides-concept': Components.AppSlidesConceptAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {}
  var HTMLAppLogoElement: {
    prototype: HTMLAppLogoElement;
    new (): HTMLAppLogoElement;
  };

  interface HTMLAppMenuFooterElement extends Components.AppMenuFooter, HTMLStencilElement {}
  var HTMLAppMenuFooterElement: {
    prototype: HTMLAppMenuFooterElement;
    new (): HTMLAppMenuFooterElement;
  };

  interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {}
  var HTMLAppNavigationElement: {
    prototype: HTMLAppNavigationElement;
    new (): HTMLAppNavigationElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppComponentsChartElement extends Components.AppComponentsChart, HTMLStencilElement {}
  var HTMLAppComponentsChartElement: {
    prototype: HTMLAppComponentsChartElement;
    new (): HTMLAppComponentsChartElement;
  };

  interface HTMLAppComponentsGifElement extends Components.AppComponentsGif, HTMLStencilElement {}
  var HTMLAppComponentsGifElement: {
    prototype: HTMLAppComponentsGifElement;
    new (): HTMLAppComponentsGifElement;
  };

  interface HTMLAppComponentsHighlightCodeElement extends Components.AppComponentsHighlightCode, HTMLStencilElement {}
  var HTMLAppComponentsHighlightCodeElement: {
    prototype: HTMLAppComponentsHighlightCodeElement;
    new (): HTMLAppComponentsHighlightCodeElement;
  };

  interface HTMLAppComponentsQrcodeElement extends Components.AppComponentsQrcode, HTMLStencilElement {}
  var HTMLAppComponentsQrcodeElement: {
    prototype: HTMLAppComponentsQrcodeElement;
    new (): HTMLAppComponentsQrcodeElement;
  };

  interface HTMLAppComponentsSocialElement extends Components.AppComponentsSocial, HTMLStencilElement {}
  var HTMLAppComponentsSocialElement: {
    prototype: HTMLAppComponentsSocialElement;
    new (): HTMLAppComponentsSocialElement;
  };

  interface HTMLAppComponentsYoutubeElement extends Components.AppComponentsYoutube, HTMLStencilElement {}
  var HTMLAppComponentsYoutubeElement: {
    prototype: HTMLAppComponentsYoutubeElement;
    new (): HTMLAppComponentsYoutubeElement;
  };

  interface HTMLAppDeckNavigationElement extends Components.AppDeckNavigation, HTMLStencilElement {}
  var HTMLAppDeckNavigationElement: {
    prototype: HTMLAppDeckNavigationElement;
    new (): HTMLAppDeckNavigationElement;
  };

  interface HTMLAppDeckPagerElement extends Components.AppDeckPager, HTMLStencilElement {}
  var HTMLAppDeckPagerElement: {
    prototype: HTMLAppDeckPagerElement;
    new (): HTMLAppDeckPagerElement;
  };

  interface HTMLAppDeckSizeElement extends Components.AppDeckSize, HTMLStencilElement {}
  var HTMLAppDeckSizeElement: {
    prototype: HTMLAppDeckSizeElement;
    new (): HTMLAppDeckSizeElement;
  };

  interface HTMLAppEditDefaultElement extends Components.AppEditDefault, HTMLStencilElement {}
  var HTMLAppEditDefaultElement: {
    prototype: HTMLAppEditDefaultElement;
    new (): HTMLAppEditDefaultElement;
  };

  interface HTMLAppEditMarkdownElement extends Components.AppEditMarkdown, HTMLStencilElement {}
  var HTMLAppEditMarkdownElement: {
    prototype: HTMLAppEditMarkdownElement;
    new (): HTMLAppEditMarkdownElement;
  };

  interface HTMLAppInstallationElement extends Components.AppInstallation, HTMLStencilElement {}
  var HTMLAppInstallationElement: {
    prototype: HTMLAppInstallationElement;
    new (): HTMLAppInstallationElement;
  };

  interface HTMLAppIntroductionElement extends Components.AppIntroduction, HTMLStencilElement {}
  var HTMLAppIntroductionElement: {
    prototype: HTMLAppIntroductionElement;
    new (): HTMLAppIntroductionElement;
  };

  interface HTMLAppSlideAuthorElement extends Components.AppSlideAuthor, HTMLStencilElement {}
  var HTMLAppSlideAuthorElement: {
    prototype: HTMLAppSlideAuthorElement;
    new (): HTMLAppSlideAuthorElement;
  };

  interface HTMLAppSlideChartElement extends Components.AppSlideChart, HTMLStencilElement {}
  var HTMLAppSlideChartElement: {
    prototype: HTMLAppSlideChartElement;
    new (): HTMLAppSlideChartElement;
  };

  interface HTMLAppSlideCodeElement extends Components.AppSlideCode, HTMLStencilElement {}
  var HTMLAppSlideCodeElement: {
    prototype: HTMLAppSlideCodeElement;
    new (): HTMLAppSlideCodeElement;
  };

  interface HTMLAppSlideContentElement extends Components.AppSlideContent, HTMLStencilElement {}
  var HTMLAppSlideContentElement: {
    prototype: HTMLAppSlideContentElement;
    new (): HTMLAppSlideContentElement;
  };

  interface HTMLAppSlideGifElement extends Components.AppSlideGif, HTMLStencilElement {}
  var HTMLAppSlideGifElement: {
    prototype: HTMLAppSlideGifElement;
    new (): HTMLAppSlideGifElement;
  };

  interface HTMLAppSlideQrcodeElement extends Components.AppSlideQrcode, HTMLStencilElement {}
  var HTMLAppSlideQrcodeElement: {
    prototype: HTMLAppSlideQrcodeElement;
    new (): HTMLAppSlideQrcodeElement;
  };

  interface HTMLAppSlideSplitElement extends Components.AppSlideSplit, HTMLStencilElement {}
  var HTMLAppSlideSplitElement: {
    prototype: HTMLAppSlideSplitElement;
    new (): HTMLAppSlideSplitElement;
  };

  interface HTMLAppSlideTitleElement extends Components.AppSlideTitle, HTMLStencilElement {}
  var HTMLAppSlideTitleElement: {
    prototype: HTMLAppSlideTitleElement;
    new (): HTMLAppSlideTitleElement;
  };

  interface HTMLAppSlideYoutubeElement extends Components.AppSlideYoutube, HTMLStencilElement {}
  var HTMLAppSlideYoutubeElement: {
    prototype: HTMLAppSlideYoutubeElement;
    new (): HTMLAppSlideYoutubeElement;
  };

  interface HTMLAppSlidesBackgroundElement extends Components.AppSlidesBackground, HTMLStencilElement {}
  var HTMLAppSlidesBackgroundElement: {
    prototype: HTMLAppSlidesBackgroundElement;
    new (): HTMLAppSlidesBackgroundElement;
  };

  interface HTMLAppSlidesConceptElement extends Components.AppSlidesConcept, HTMLStencilElement {}
  var HTMLAppSlidesConceptElement: {
    prototype: HTMLAppSlidesConceptElement;
    new (): HTMLAppSlidesConceptElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-footer': HTMLAppFooterElement
    'app-logo': HTMLAppLogoElement
    'app-menu-footer': HTMLAppMenuFooterElement
    'app-navigation': HTMLAppNavigationElement
    'app-home': HTMLAppHomeElement
    'app-components-chart': HTMLAppComponentsChartElement
    'app-components-gif': HTMLAppComponentsGifElement
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement
    'app-components-qrcode': HTMLAppComponentsQrcodeElement
    'app-components-social': HTMLAppComponentsSocialElement
    'app-components-youtube': HTMLAppComponentsYoutubeElement
    'app-deck-navigation': HTMLAppDeckNavigationElement
    'app-deck-pager': HTMLAppDeckPagerElement
    'app-deck-size': HTMLAppDeckSizeElement
    'app-edit-default': HTMLAppEditDefaultElement
    'app-edit-markdown': HTMLAppEditMarkdownElement
    'app-installation': HTMLAppInstallationElement
    'app-introduction': HTMLAppIntroductionElement
    'app-slide-author': HTMLAppSlideAuthorElement
    'app-slide-chart': HTMLAppSlideChartElement
    'app-slide-code': HTMLAppSlideCodeElement
    'app-slide-content': HTMLAppSlideContentElement
    'app-slide-gif': HTMLAppSlideGifElement
    'app-slide-qrcode': HTMLAppSlideQrcodeElement
    'app-slide-split': HTMLAppSlideSplitElement
    'app-slide-title': HTMLAppSlideTitleElement
    'app-slide-youtube': HTMLAppSlideYoutubeElement
    'app-slides-background': HTMLAppSlidesBackgroundElement
    'app-slides-concept': HTMLAppSlidesConceptElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-footer': HTMLAppFooterElement;
    'app-logo': HTMLAppLogoElement;
    'app-menu-footer': HTMLAppMenuFooterElement;
    'app-navigation': HTMLAppNavigationElement;
    'app-home': HTMLAppHomeElement;
    'app-components-chart': HTMLAppComponentsChartElement;
    'app-components-gif': HTMLAppComponentsGifElement;
    'app-components-highlight-code': HTMLAppComponentsHighlightCodeElement;
    'app-components-qrcode': HTMLAppComponentsQrcodeElement;
    'app-components-social': HTMLAppComponentsSocialElement;
    'app-components-youtube': HTMLAppComponentsYoutubeElement;
    'app-deck-navigation': HTMLAppDeckNavigationElement;
    'app-deck-pager': HTMLAppDeckPagerElement;
    'app-deck-size': HTMLAppDeckSizeElement;
    'app-edit-default': HTMLAppEditDefaultElement;
    'app-edit-markdown': HTMLAppEditMarkdownElement;
    'app-installation': HTMLAppInstallationElement;
    'app-introduction': HTMLAppIntroductionElement;
    'app-slide-author': HTMLAppSlideAuthorElement;
    'app-slide-chart': HTMLAppSlideChartElement;
    'app-slide-code': HTMLAppSlideCodeElement;
    'app-slide-content': HTMLAppSlideContentElement;
    'app-slide-gif': HTMLAppSlideGifElement;
    'app-slide-qrcode': HTMLAppSlideQrcodeElement;
    'app-slide-split': HTMLAppSlideSplitElement;
    'app-slide-title': HTMLAppSlideTitleElement;
    'app-slide-youtube': HTMLAppSlideYoutubeElement;
    'app-slides-background': HTMLAppSlidesBackgroundElement;
    'app-slides-concept': HTMLAppSlidesConceptElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
